export async function DisplayHomeInformation(homeContainerClass) {
    const homeContainer = document.querySelector(homeContainerClass);
    const heroSection = document.createElement('div');
    const heroImage = document.createElement('img');
    const callToAction = document.createElement('button');
    const homeHeader = document.createElement('h1');
    const contentSection = document.createElement('div');
    const currentEventsSection = document.createElement('section');
    const currentEventsSectionHeader = document.createElement('h2');
    const currentEventsSectionContainer = document.createElement('div');
    const weatherSection = document.createElement('section');
    const weatherSectionHeader = document.createElement('h2');
    const weatherSectionContainer = document.createElement('div');
    const forecastSection = document.createElement('section');
    const forecastSectionHeader = document.createElement('h2');
    const forecastSectionContainer = document.createElement('div');
    const siteSpotlightSection = document.createElement('section');
    const siteSpotlightSectionHeader = document.createElement('h2');
    const siteSpotlightSectionContainer = document.createElement('div');
    const foodSpotlightSection = document.createElement('section');
    const foodSpotlightSectionHeader = document.createElement('h2');
    const foodSpotlightSectionContainer = document.createElement('div');
    const attractionSpotlightSection = document.createElement('section');
    const attractionSpotlightSectionHeader = document.createElement('h2');
    const attractionSpotlightSectionContainer = document.createElement('div');

    heroSection.classList.add('heroSection');
    heroImage.classList.add('heroImage');
    callToAction.classList.add('callToAction');
    callToAction.classList.add('science-gothic-regular');
    homeHeader.classList.add('homeHeader');
    homeHeader.classList.add('science-gothic-regular');
    contentSection.classList.add('contentSection');
    currentEventsSection.classList.add('currentEventsSection');
    currentEventsSectionHeader.classList.add('currentEventsSectionHeader');
    currentEventsSectionContainer.classList.add('currentEventsSectionContainer');
    weatherSection.classList.add('weatherSection');
    weatherSectionHeader.classList.add('weatherSectionHeader');
    weatherSectionContainer.classList.add('weatherSectionContainer');
    forecastSection.classList.add('forecastSection');
    forecastSectionHeader.classList.add('forecastSectionHeader');
    forecastSectionContainer.classList.add('forecastSectionContainer');
    siteSpotlightSection.classList.add('siteSpotlightSection');
    siteSpotlightSectionHeader.classList.add('siteSpotlightSectionHeader');
    siteSpotlightSectionContainer.classList.add('siteSpotlightSectionContainer');
    foodSpotlightSection.classList.add('foodSpotlightSection');
    foodSpotlightSectionHeader.classList.add('foodSpotlightSectionHeader');
    foodSpotlightSectionContainer.classList.add('foodSpotlightSectionContainer');
    attractionSpotlightSection.classList.add('attractionSpotlightSection');
    attractionSpotlightSectionHeader.classList.add('attractionSpotlightSectionHeader');
    attractionSpotlightSectionContainer.classList.add('attractionSpotlightSectionContainer');

    heroImage.src = 'images/hero.webp';
    heroImage.alt = 'Hero Image';
    callToAction.textContent = 'Explore';
    homeHeader.textContent = 'Home';
    currentEventsSectionHeader.textContent = 'Current Events / News';
    weatherSectionHeader.textContent = 'Weather';
    forecastSectionHeader.textContent = 'Forecast';
    siteSpotlightSectionHeader.textContent = 'Site Spotlight';
    foodSpotlightSectionHeader.textContent = 'Food Spotlight';
    attractionSpotlightSectionHeader.textContent = 'Attraction Spotlight';

    heroSection.appendChild(heroImage);
    heroSection.appendChild(callToAction);
    currentEventsSection.appendChild(currentEventsSectionHeader);
    currentEventsSection.appendChild(currentEventsSectionContainer);
    contentSection.appendChild(currentEventsSection);
    weatherSection.appendChild(weatherSectionHeader);
    weatherSection.appendChild(weatherSectionContainer);
    contentSection.appendChild(weatherSection);
    forecastSection.appendChild(forecastSectionHeader);
    forecastSection.appendChild(forecastSectionContainer);
    contentSection.appendChild(forecastSection);
    siteSpotlightSection.appendChild(siteSpotlightSectionHeader);
    siteSpotlightSection.appendChild(siteSpotlightSectionContainer);
    contentSection.appendChild(siteSpotlightSection);
    foodSpotlightSection.appendChild(foodSpotlightSectionHeader);
    foodSpotlightSection.appendChild(foodSpotlightSectionContainer);
    contentSection.appendChild(foodSpotlightSection);
    attractionSpotlightSection.appendChild(attractionSpotlightSectionHeader);
    attractionSpotlightSection.appendChild(attractionSpotlightSectionContainer);
    contentSection.appendChild(attractionSpotlightSection);

    homeContainer.appendChild(heroSection);
    homeContainer.appendChild(homeHeader);
    homeContainer.appendChild(contentSection);
}